package com.imagekit.android.util

internal object TranformationMapping {
    const val width = "w"
    const val height = "h"
    const val aspectRatio = "ar"
    const val crop = "c"
    const val cropMode = "cm"
    const val focus = "fo"
    const val quality = "q"
    const val format = "f"
    const val blur = "bl"
    const val eGrayscale = "e-grayscale"
    const val dpr = "dpr"
    const val namedTransformation = "n"
    const val defaultImage = "di"
    const val progressiveJPEG = "pr"
    const val lossless = "lo"
    const val trimEdges = "t"
    const val overlayImage = "oi"
    const val overlayFocus = "ofo"
    const val overlayX = "ox"
    const val overlayY = "oy"
    const val overlayWidth = "ow"
    const val overlayHeight = "oh"
    const val overlayText = "ot"
    const val overlayTextColor = "otc"
    const val overlayTextFont = "otf"
    const val overlayTextSize = "ots"
    const val overlayTextTypography = "ott"
    const val overlayTransparency = "oa"
    const val overlayBackground = "obg"
    const val colorProfile = "cp"
    const val imageMetadata = "md"
    const val rotate = "rt"
    const val radius = "r"
    const val backgroundColor = "bg"
    const val border = "b"
    const val contrastStretch = "e-contrast"
    const val sharpen = "e-sharpen"
    const val unsharpMask = "e-usm"
    const val transformationStep = ":"
}