package com.imagekit.android.util

internal object TransformationMapping {
    const val height = "h"
    const val width = "w"
    const val aspectRatio = "ar"
    const val quality = "q"
    const val crop = "c"
    const val cropMode = "cm"
    const val x = "x"
    const val y = "y"
    const val focus = "fo"
    const val format = "f"
    const val radius = "r"
    const val background = "bg"
    const val border = "b"
    const val rotation = "rt"
    const val blur = "bl"
    const val named = "n"
    const val progressive = "pr"
    const val lossless = "lo"
    const val trim = "t"
    const val metadata = "md"
    const val colorProfile = "cp"
    const val defaultImage = "di"
    const val dpr = "dpr"
    const val effectSharpen = "e-sharpen"
    const val effectUSM = "e-usm"
    const val effectContrast = "e-contrast"
    const val effectGray = "e-grayscale"
    const val original = "orig"
    const val transformationStep = ":"
    const val streamingResolution="sr"
}